blueprint:
  name: Robb smarrt 4 channel remote controller
  description: 'This blueprint is for the  Robb smarrt 4 channel remote control (ROBB
    ROB_200-024-0) when used with zha.

    It is for general use so all oval buttons (1-4, S1 and S2) can be connected to any action of your choice. The (1) and (0) button will activate buuton 1 till 4 is a sequence.
    This remote supports short button clicks and long button presses (over 4 seconds)

    Make sure to select the correct sensor for the remote.

    '
  domain: automation
  source_url: https://github.com/Bekkie/ha-blueprints/blob/main/automation/robb-smarrt-4-ch-remote-ROB_200-024-0.yaml
  input:
    remote:
      name: Remote
      description: Switch remote to use
      selector:
        device:
          model: ROB_200-024-0

    on_button_1_short:
      name: On button 1 - short
      default: []
      selector:
        action: {}
    off_button_1_short:
      name: Off button 1 - short
      default: []
      selector:
        action: {}
    on_button_1_long:
      name: On button 1 - long press
      default: []
      selector:
        action: {}
    off_button_1_long:
      name: Off button 1 - long press
      default: []
      selector:
        action: {}
    on_button_2_short:
      name: On button 2 - short
      default: []
      selector:
        action: {}
    off_button_2_short:
      name: Off button 2 - short
      default: []
      selector:
        action: {}
    on_button_2_long:
      name: On button 2 - long press
      default: []
      selector:
        action: {}
    off_button_2_long:
      name: Off button 2 - long press
      default: []
      selector:
        action: {}
    on_button_3_short:
      name: On button 3 - short
      default: []
      selector:
        action: {}
    off_button_3_short:
      name: Off button 3 - short
      default: []
      selector:
        action: {}
    on_button_3_long:
      name: On button 3 - long press
      default: []
      selector:
        action: {}
    off_button_3_long:
      name: Off button 3 - long press
      default: []
      selector:
        action: {}
    on_button_4_short:
      name: On button 4 - short
      default: []
      selector:
        action: {}
    off_button_4_short:
      name: Off button 4 - short
      default: []
      selector:
        action: {}
    on_button_4_long:
      name: On button 4 - long press
      default: []
      selector:
        action: {}
    off_button_4_long:
      name: Off button 4 - long press
      default: []
      selector:
        action: {}
    s1_button_short:
      name: S1 button - short
      default: []
      selector:
        action: {}
    s2_button_short:
      name: S2 button - short
      default: []
      selector:
        action: {}
    s1_button_long:
      name: S1 button - long press
      default: []
      selector:
        action: {}
    s2_button_long:
      name: S2 button - long press
      default: []
      selector:
        action: {}
mode: parallel
max_exceeded: silent
trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input remote
action:
- variables:
    button: '{{ trigger.event.data.endpoint_id }}'
    cmd: '{{ trigger.event.data.command }}'
    args: '{{ trigger.event.data.args }}'
- choose:
  - conditions:
    - '{{ button == 1 and cmd == ''on'' }}'
    sequence: !input on_button_1_short
  - conditions:
    - '{{ button == 1 and cmd == ''off'' }}'
    sequence: !input off_button_1_short
  - conditions:
    - '{{ button == 1 and cmd == ''move_with_on_off'' }}'
    sequence:
    - if:
      - condition:
        - '{{ args[11] == "U" }}'
      then: !input on_button_1_long
      else: !input off_button_1_long
  - conditions:
    - '{{ button == 2 and cmd == ''on'' }}'
    sequence: !input on_button_2_short
  - conditions:
    - '{{ button == 2 and cmd == ''off'' }}'
    sequence: !input off_button_2_short
  - conditions:
    - '{{ button == 2 and cmd == ''move_with_on_off'' }}'
    sequence:
    - if:
      - condition:
        - '{{ args[11] == "U" }}'
      then: !input on_button_2_long
      else: !input off_button_2_long
  - conditions:
    - '{{ button == 3 and cmd == ''on'' }}'
    sequence: !input on_button_3_short
  - conditions:
    - '{{ button == 3 and cmd == ''off'' }}'
    sequence: !input off_button_3_short
  - conditions:
    - '{{ button == 3 and cmd == ''move_with_on_off'' }}'
    sequence:
    - if:
      - condition:
        - '{{ args[11] == "U" }}'
      then: !input on_button_3_long
      else: !input off_button_3_long
  - conditions:
    - '{{ button == 4 and cmd == ''on'' }}'
    sequence: !input on_button_4_short
  - conditions:
    - '{{ button == 4 and cmd == ''off'' }}'
    sequence: !input off_button_4_short
  - conditions:
    - '{{ button == 4 and cmd == ''move_with_on_off'' }}'
    sequence:
    - if:
      - condition:
        - '{{ args[11] == "U" }}'
      then: !input on_button_4_long
      else: !input off_button_4_long
  - conditions:
    - '{{ button == 1 and cmd == ''recall'' }}'
    sequence: 
    - if:
      - condition:
        - '{{ args[1] == 1 }}'
      then: !input s1_button_short
      else: !input s2_button_short
  - conditions:
    - '{{ button == 1 and cmd == ''store'' }}'
    sequence: 
    - if:
      - condition:
        - '{{ args[1] == 1 }}'
      then: !input s1_button_long
      else: !input s2_button_long
